version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch-oss:7.2.0
    container_name: elasticsearch
    networks:
      - reactivesearch
    environment:
    - bootstrap.memory_lock=true
    - discovery.type=single-node
    - "ES_JAVA_OPTS=-Xms1g -Xmx1g"
    ulimits:
      nproc: 65536
      nofile:
        soft: 65536
        hard: 65536
      memlock:
        soft: -1
        hard: -1
    ports:
      - 9200:9200
  reactivesearch:
    build: ./
    container_name: reactivesearch
    env_file:
      - config/docker.env
    networks:
      - reactivesearch
    restart: on-failure
    ports:
      - 8000:8000
    depends_on:
      - elasticsearch

networks:
  reactivesearch:
    driver: bridge
