name: build binary
on:
  push:
    branches: [feat/github-actions]
    # Publish semver tags as releases.
    tags: ['*.*.*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Set VERSION env
        run: echo VERSION=7.52.0
      - name: building binaries for eaas deployments
        uses: appleboy/ssh-action@master
        env:
          VERSION: ${{VERSION}}
        with:
          host: ${{ secrets.GCLOUD_BUILD_HOST }}
          username: ${{ secrets.GCLOUD_BUILD_USERNAME }}
          key: ${{ secrets.GCLOUD_BUILD_KEY }}
          port: 22
          envs: VERSION
          script: |
            echo ${VERSION}
            sh build.sh
      - name: building binaries for ami
        uses: appleboy/ssh-action@master
        env:
          VERSION: ${{VERSION}}
        with:
          host: ${{ secrets.AWS_BUILD_HOST }}
          username: ${{ secrets.AWS_BUILD_USERNAME }}
          key: ${{ secrets.AWS_BUILD_KEY }}
          port: 22
          envs: VERSION
          script: |
            echo ${VERSION}
            sh build.sh
