name: build binary
on:
  push:
    branches: [feat/github-actions]
    # Publish semver tags as releases.
    # tags: ['*.*.*']
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: building binaries for eaas deployments
        uses: appleboy/ssh-action@master
        env:
          VERSION: '7.52.0'
        with:
          host: ${{ secrets.GCLOUD_BUILD_HOST }}
          username: ${{ secrets.GCLOUD_BUILD_USERNAME }}
          key: ${{ secrets.GCLOUD_BUILD_KEY }}
          port: 22
          timeout: 3600s
          command_timeout: 3600s
          envs: VERSION
          script: |
            echo ${VERSION}
            sh build.sh ${VERSION}
      - name: building binaries for ami
        uses: appleboy/ssh-action@master
        env:
          VERSION: '7.52.0'
        with:
          host: ${{ secrets.AWS_BUILD_HOST }}
          username: ${{ secrets.AWS_BUILD_USERNAME }}
          key: ${{ secrets.AWS_BUILD_KEY }}
          port: 22
          envs: VERSION
          script: |
            echo ${VERSION}
            sh build.sh ${VERSION}
